# Importing Libraries

In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import sklearn
from sklearn import preprocessing

# Reading the Dataset

In [2]:
data=pd.read_excel('iris2.xls')

In [3]:
data.head()

SL   SW   PL   PW Classification
0  5.1  3.5  1.4  0.2    Iris-setosa
1  4.9  3.0  1.4  0.2    Iris-setosa
2  NaN  3.2  1.3  0.2    Iris-setosa
3  4.6  3.1  1.5  0.2    Iris-setosa
4  5.0  3.6  1.4  0.2    Iris-setosa

# Pre-Processing

## Handling Missing Values

In [4]:
data.isnull().sum()

SL                7
SW                6
PL                6
PW                0
Classification    0
dtype: int64

In [5]:
data['SL']=data['SL'].fillna(data['SL'].mode()[0])
data['SW']=data['SW'].fillna(data['SW'].mode()[0])
data['PW']=data['PW'].fillna(data['PW'].mode()[0])
data['PL']=data['PL'].fillna(data['PL'].mode()[0])

In [6]:
data.isnull().sum()

SL                0
SW                0
PL                0
PW                0
Classification    0
dtype: int64

## Encoding

In [7]:
label_encoder = preprocessing.LabelEncoder()
data['Classification'] = label_encoder.fit_transform(data['Classification'])

In [8]:
X = data.drop('Classification', axis=1)
y = data[ 'Classification' ]

## Train Test Splitting

In [9]:
from sklearn.model_selection import train_test_split

In [10]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Support Vector Classifier

In [11]:
from sklearn.svm import SVC

In [12]:
clf_svm = SVC(kernel='linear')
clf_svm = clf_svm.fit(X_train, y_train)
y_pred_svm = clf_svm.predict(X_test)

In [13]:
from sklearn.metrics import accuracy_score, confusion_matrix

In [14]:
confusion_matrix(y_test, y_pred_svm)

array([[10,  0,  0],
       [ 0,  8,  1],
       [ 0,  0, 11]], dtype=int64)

In [15]:
accuracy_score(y_test, y_pred_svm)

0.9666666666666667

In [16]:
clf_svm2 = SVC(kernel='rbf')
clf_svm2 = clf_svm2.fit(X_train, y_train)
y_pred_svm2 = clf_svm2.predict(X_test)

In [17]:
accuracy_score(y_test, y_pred_svm2)

0.9666666666666667

# Decision Tree Classifier

In [18]:
from sklearn.tree import DecisionTreeClassifier

In [19]:
dt_clf = DecisionTreeClassifier()
df_clf = dt_clf.fit(X_train, y_train)
y_pred_dt = dt_clf.predict(X_test)

In [20]:
confusion_matrix(y_test, y_pred_dt)

array([[10,  0,  0],
       [ 0,  9,  0],
       [ 0,  0, 11]], dtype=int64)

In [21]:
accuracy_score(y_test, y_pred_dt)

1.0

# Random Forest Classifier

In [22]:
from sklearn.ensemble import RandomForestClassifier

In [23]:
rf_clf = RandomForestClassifier()
rf_clf = rf_clf.fit(X_train, y_train)
y_pred_clf = rf_clf.predict(X_test)

In [24]:
confusion_matrix(y_test, y_pred_clf)

array([[10,  0,  0],
       [ 0,  9,  0],
       [ 0,  0, 11]], dtype=int64)

In [25]:
accuracy_score(y_test, y_pred_clf)

1.0

### Both Random Forest & Decision Tree classification models gave the best and same results